### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#20]
Hi Stephen
I found an error on the phpbb administration page.
log into your phpbb administrator account, go to the "extensions" menu. you have the following error
:

`Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.`

**Comment by sbillard** [comment]
This is a known issue with PHPBBS. (See the board posts.) none of the solutions suggested worked for me. 

But it really does not seem to be an issue. I am not sure even what that tab is supposed to do.  Extensions are installed via FTP and managed on the configuration tab.

**Comment by sbillard** [comment]
Issue reported to PHPBBS support: https://tracker.phpbb.com/browse/PHPBB3-16387?filter=-2

**Comment by sbillard** [comment]
This has been traced down to an incompatibility between the Akismet Anti-Spam extension and phpBBS 3.3. See https://www.phpbb.com/customise/db/extension/akismet/support/topic/212311

Although the Akismet extension author acknowledges the problem and supposedly has a fix. When I tried the current GitHub version of the extension it did not resolve the issue. Also the author has not made any official update to the extension.

For now, the extension is disabled. Hopefully there will be a solution in the near future.

**Comment by sbillard** [comment]
I have installed Antispam by CleanTalk in place of Akismet. If and when Akismet gets fixed I will revisit this choice. In the mean time, the issue is closed.
