### ISSUE TITLE
Add more content to the home page

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#22]
Add more content to the home page to further explain how NPG works:
For users who visit the NPG website it would be interesting to explain the functions of Image, Video, Audio, Blog, Pages, User Rights, Multi User, Multilanguage ...

**Comment by sbillard** [comment]
How would this be different from the user guide?

**Comment by By-oussef** [comment]
This is information that is extremely important because the home page of a website must present the functionality of the software. For example, consult the cms wordpress home page
the page is quite complete and presents the functionality of wordpress. npg must present the features of the software to users.

**Comment by sbillard** [comment]
Please then create the content and update the repository website with your suggestions. I will close this ticket since when you do a pull request with your proposed changes it will create its own ticket.

**Comment by By-oussef** [comment]
I created this ticket because I read this article about SEO and content. The more content a site has, the higher it will rank in the search engine ranking. Stephen I think we need to add more content on the home page.

https://www.webfx.com/content-marketing/content-marketing-improve-SEO.html

**Comment by sbillard** [comment]
To add more content there must be content to add. So If you think more is needed, then come up with the content to add. Otherwise you are as the saying goes "just pissing in the wind"
