### ISSUE TITLE
Change the menu bar vertical to horizontal

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#23]
The menu bar is extremely important because it allows you to navigate on the different pages of the NPG site because it would be interesting to put it at the top.

**Comment by sbillard** [comment]
I think I have mentioned before that the website is in a github repository. You can always make changes to the site and submit a pull request.  But personally I do not see the need for a change. Menu bars at the top can be a problem by themselves if they scroll off the screen. One of the major changes to the netPhotoGraphics back end was to modernize the top menu bar by moving it to the left side of the page.
