### ISSUE TITLE
Which file to edit to modify the header ?

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#24]
Hi Stephen,
What is the file to edit to modify the header I looked for but I did not find the file. Can you give me the name of the folder and file to edit.
Thank you

**Comment by sbillard** [comment]
I am not sure what you are referring to as "the header".  But if you are planning on modifying the website theme, your first task is to familiarize yourself with the theme in general. Modifying one part without an understanding of the whole is a road to disaster.
