### ISSUE TITLE
Add .po files for translation

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#31]
Hi Stephen
Can you add .po files for translation i would like to translate npg website to french, spanish and italian.
Thank You

**Comment by sbillard** [comment]
There are currently .PO files for these languages.  Standard (eg. theme defined strings will be in those.) If you insure you have the most recent string (do an update from source) you can make a ticket and add your updated .PO files to it. Pull requests for these files have caused lots of problems in the past, so just including the files on a ticket works best.

Site specific text has to be updated in the objects themselves. I am not sure what the best way to handle updates to these. Perhaps a nPG backup of the particular table. We can at least try that. I will do such a backup of the current content and add it to the repository. We'll see how that goes.

**Comment by sbillard** [comment]
Ok, I did some experimentation. First, the only site specific things needing translation are the pates. (The site does not make use of news articles at this point. That is the function of the Forum.)

Of these, the release notes is a problem. They are generated automatically by my release process and are not actually stored in the database. I think the best solution to these is to put a Google Translate button on the page.

For the other content, I have placed a database backup of the site in the repository. You can load that into your local copy of the website.  When you load it in you should uncheck all the tables except for the pages table.

Make your translations and then make a database backup of your pages. (Currently you have to back up the whole database, but I think I will change that.) Attach the backup to a ticket and I can then get it into the repository and onto the site.

**Comment by sbillard** [comment]
I have implemented the selective table backup. Please use the DEV version 2.00.04.11.03 or more recent when you are backing up the pages table for submission.

**Comment by sbillard** [comment]
The Google Translate button is now included on the release notes page. The rest is up to you. I will close this ticket now as you have the tools to make the translations.
