### ISSUE TITLE
Add Share On extension for phpbb

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#32]
Hi Stephen 
Can you add this extension for phpbb : 
Share On is an extension that allows users to share topics and posts in the following social networks:

    Facebook
    Twitter
    Digg
    Reddit
    Delicious
    VK
    Tuenti
    Tumblr
    Google+
    Whatsapp

https://www.phpbb.com/customise/db/extension/shareon/

**Comment by sbillard** [comment]
This plugin has not been validated for PhpBBS 3.3. Given the problems the site had with a different plugin which was not compatible with 3.3 I will not add this at this time.
