### ISSUE TITLE
Change the current theme and integrate Bootstrap

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#35]
Hello, Stephen I hope you are well.

I create this post because I documented myself on the internet to see that it was the best technology at the moment concerning graphic design. I found the Bootstrap technolohgie which is very advanced because it uses a grid system. We don't need to have a computer version and a mobile version. Bootrstap is responsive and automatically adapts to all screens without having additional files. In addition, bootstrap technology uses cdn technology which increases the speed of loading the site and therefore its performance.

Exemple : https://getbootstrap.com/docs/4.4/examples/jumbotron/

THank You for the importance you will give to this post

**Comment by sbillard** [comment]
If you wish to create such a theme, by all means do it. But there is no need to create a ticket until you have done so.

**Comment by By-oussef** [comment]
[startbootstrap-scrolling-nav-gh-pages.zip](https://github.com/netPhotoGraphics/Website/files/4389888/startbootstrap-scrolling-nav-gh-pages.zip)

**Comment by sbillard** [comment]
This is not a nPG theme, so is pretty useless.

**Comment by By-oussef** [comment]
WStephen we can use zpBootstrap

**Comment by sbillard** [comment]
Again, if you wish to create a custom nPG theme, by all means do so and we will evaluate it. Otherwise you are not contributing anything by these tickets.
