### ISSUE TITLE
Use CDN for MobileJquery - CSS and JS 

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#38]
Use CDN for MobileJquery - CSS and JS 

Link to CDN Google for Js:  http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.js
Link to CDN Google for css : http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.css

**Comment by sbillard** [comment]
Why on earth would we do this? Jquery mobile is provided by the mobile theme.
