### ISSUE TITLE
Add Google Analitycs for phpbb

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#40]
Hi Stephen can you add this plugin to phpbb.
Thank You

[phpbb_google-analitycs.zip](https://github.com/netPhotoGraphics/Website/files/4403053/phpbb_google-analitycs.zip)

**Comment by sbillard** [comment]
done

**Comment by By-oussef** [comment]
Hi Stephen the file you added is the one I attached up.
Because i just make a test and google analitycs dont work.
Thank You

**Comment by sbillard** [comment]
If there is something different from the official plugin you must make a separate file of it in the repository. Otherwise if the site has to be rebuilt no one will know to add the file.

**Comment by By-oussef** [comment]
ok thank you Stephen.

**Comment by By-oussef** [comment]
i make pull request
